/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import Control.Intructor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class RegistroInstru extends javax.swing.JFrame {
      
    
    
    
    
    Conexion.conexion con = new Conexion.conexion();
    Connection cn = con.conectar();
    public RegistroInstru() {
        initComponents();
        setTitle("Registro (Instructor)");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CedulaI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CorrEI = new javax.swing.JTextField();
        NumT1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PasswordI = new javax.swing.JPasswordField();
        NombreCompleI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DireccioI = new javax.swing.JTextField();
        Direc = new javax.swing.JLabel();
        UserI = new javax.swing.JTextField();
        EspecialidadI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Crear Usuario Instructor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel2.setText("Numero de Cedula");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 110, -1));

        CedulaI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaIActionPerformed(evt);
            }
        });
        jPanel2.add(CedulaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel4.setText("Correo electronico");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, -1));

        CorrEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrEIActionPerformed(evt);
            }
        });
        jPanel2.add(CorrEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 270, -1));

        NumT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumT1ActionPerformed(evt);
            }
        });
        jPanel2.add(NumT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel5.setText("Número de telefónico");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 80, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, 50));

        PasswordI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordIActionPerformed(evt);
            }
        });
        jPanel2.add(PasswordI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 330, -1));

        NombreCompleI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCompleIActionPerformed(evt);
            }
        });
        jPanel2.add(NombreCompleI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel1.setText("Nombre Completo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, -1));

        edI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edI.setAlignmentX(55.0F);
        edI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edIActionPerformed(evt);
            }
        });
        jPanel2.add(edI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 60, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Edad");
        jLabel7.setAlignmentX(55.0F);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        DireccioI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccioIActionPerformed(evt);
            }
        });
        jPanel2.add(DireccioI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 270, -1));

        Direc.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        Direc.setText("Dirección");
        jPanel2.add(Direc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, -1));
        jPanel2.add(UserI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, -1));
        jPanel2.add(EspecialidadI, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel8.setText("Especialidad");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel9.setText("Nombre de usuario instructor");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 450, 330));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trasparencia.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 510, 380));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro3.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edIActionPerformed

    private void CedulaIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaIActionPerformed

    private void CorrEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrEIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorrEIActionPerformed

    private void NumT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumT1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String Nombre = NombreCompleI.getText();
        String Ced = CedulaI.getText();
        String CorrEl = CorrEI.getText();
        String Tel = NumT1.getText();
        String Pass = PasswordI.getText();
        String edad = edI.getText();
        String Direc = DireccioI.getText();
        String User = UserI.getText();
        String especialidadI = EspecialidadI.getText();
        if (Nombre.isEmpty() || Ced.isEmpty() || CorrEl.isEmpty() || Tel.isEmpty() || Pass.isEmpty() || edad.isEmpty() || Direc.isEmpty() || User.isEmpty() || especialidadI.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error al ingresar al sistema, debe llenar todas las casillas.");
        } else {
        Intructor inst = new Intructor(Nombre, edad, Direc, Tel, Integer.parseInt(Ced), 0, CorrEl, CorrEl);
        inst.AñadiraBasedeDatos(cn, Nombre, edad, Direc, Tel, Ced, CorrEl, especialidadI, Pass, User);
         dispose(); // Cerrar la ventana actual (registro)
                PantallaPrincipal MPTN = new PantallaPrincipal();
                MPTN.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PasswordIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordIActionPerformed

    private void NombreCompleIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCompleIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCompleIActionPerformed

    private void DireccioIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccioIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccioIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroInstru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroInstru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroInstru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroInstru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroInstru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CedulaI;
    private javax.swing.JTextField CorrEI;
    private javax.swing.JLabel Direc;
    private javax.swing.JTextField DireccioI;
    private javax.swing.JTextField EspecialidadI;
    private javax.swing.JTextField NombreCompleI;
    private javax.swing.JTextField NumT1;
    private javax.swing.JPasswordField PasswordI;
    private javax.swing.JTextField UserI;
    private javax.swing.JTextField edI;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
